apiVersion: v2
appVersion: "0.8.0"
description: A Helm chart for prometheus postgres-exporter
name: prometheus-postgres-exporter
version: 1.10.0
home: https://github.com/wrouesnel/postgres_exporter
sources:
- https://github.com/wrouesnel/postgres_exporter
keywords:
- postgresql
- prometheus
- exporter
